# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\Projects\_tools\_maya\fossilAnimTools\fossilAnimTools\spacepresetgui.ui',
# licensing of 'G:\Projects\_tools\_maya\fossilAnimTools\fossilAnimTools\spacepresetgui.ui' applies.
#
# Created: Sun Apr  5 14:11:19 2020
#      by: pyside2-uic  running on PySide2 5.11.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 1083)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.newPreset = QtWidgets.QPushButton(Form)
        self.newPreset.setObjectName("newPreset")
        self.gridLayout.addWidget(self.newPreset, 1, 2, 1, 1)
        self.newProfile = QtWidgets.QPushButton(Form)
        self.newProfile.setObjectName("newProfile")
        self.gridLayout.addWidget(self.newProfile, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.clone = QtWidgets.QPushButton(Form)
        self.clone.setObjectName("clone")
        self.gridLayout.addWidget(self.clone, 2, 4, 1, 1)
        self.profileChooser = QtWidgets.QComboBox(Form)
        self.profileChooser.setObjectName("profileChooser")
        self.gridLayout.addWidget(self.profileChooser, 2, 1, 1, 1)
        self.presetChooser = QtWidgets.QComboBox(Form)
        self.presetChooser.setObjectName("presetChooser")
        self.gridLayout.addWidget(self.presetChooser, 1, 1, 1, 1)
        self.rename = QtWidgets.QPushButton(Form)
        self.rename.setObjectName("rename")
        self.gridLayout.addWidget(self.rename, 2, 3, 1, 1)
        self.deleteProfile = QtWidgets.QPushButton(Form)
        self.deleteProfile.setObjectName("deleteProfile")
        self.gridLayout.addWidget(self.deleteProfile, 2, 5, 1, 1)
        self.characterChooser = QtWidgets.QComboBox(Form)
        self.characterChooser.setObjectName("characterChooser")
        self.gridLayout.addWidget(self.characterChooser, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.applyFrame = QtWidgets.QPushButton(self.frame)
        self.applyFrame.setObjectName("applyFrame")
        self.horizontalLayout_4.addWidget(self.applyFrame)
        self.applyRange = QtWidgets.QPushButton(self.frame)
        self.applyRange.setObjectName("applyRange")
        self.horizontalLayout_4.addWidget(self.applyRange)
        self.applySelected = QtWidgets.QPushButton(self.frame)
        self.applySelected.setObjectName("applySelected")
        self.horizontalLayout_4.addWidget(self.applySelected)
        self.applyAll = QtWidgets.QPushButton(self.frame)
        self.applyAll.setObjectName("applyAll")
        self.horizontalLayout_4.addWidget(self.applyAll)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.frame)
        self.addControls = QtWidgets.QPushButton(Form)
        self.addControls.setObjectName("addControls")
        self.verticalLayout_2.addWidget(self.addControls)
        self.profileTable = QtWidgets.QTableWidget(Form)
        self.profileTable.setLineWidth(0)
        self.profileTable.setShowGrid(False)
        self.profileTable.setCornerButtonEnabled(False)
        self.profileTable.setObjectName("profileTable")
        self.profileTable.setColumnCount(3)
        self.profileTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.profileTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.profileTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.profileTable.setHorizontalHeaderItem(2, item)
        self.profileTable.horizontalHeader().setVisible(False)
        self.profileTable.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.profileTable)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Form", "Current", None, -1))
        self.newPreset.setText(QtWidgets.QApplication.translate("Form", "New", None, -1))
        self.newProfile.setText(QtWidgets.QApplication.translate("Form", "New", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Form", "Preset", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Form", "Profile", None, -1))
        self.clone.setText(QtWidgets.QApplication.translate("Form", "Clone", None, -1))
        self.rename.setText(QtWidgets.QApplication.translate("Form", "Rename", None, -1))
        self.deleteProfile.setText(QtWidgets.QApplication.translate("Form", "Delete", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Form", "Apply", None, -1))
        self.applyFrame.setText(QtWidgets.QApplication.translate("Form", "Frame", None, -1))
        self.applyRange.setText(QtWidgets.QApplication.translate("Form", "Range", None, -1))
        self.applySelected.setText(QtWidgets.QApplication.translate("Form", "Selected", None, -1))
        self.applyAll.setText(QtWidgets.QApplication.translate("Form", "All", None, -1))
        self.addControls.setText(QtWidgets.QApplication.translate("Form", "Add Selected Controls", None, -1))
        self.profileTable.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("Form", "New Column", None, -1))
        self.profileTable.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("Form", "New Column", None, -1))
        self.profileTable.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("Form", "New Column", None, -1))

